-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 09:30:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`czytelnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`czytelnik` (
  `idCzytelnika` INT NOT NULL,
  `nazwisko` VARCHAR(45) NULL,
  `imie` VARCHAR(45) NULL,
  `adres` VARCHAR(255) NULL,
  PRIMARY KEY (`idCzytelnika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`książki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`książki` (
  `ISBN` INT NOT NULL,
  `tytul` VARCHAR(255) NULL,
  `wydawnictwo` VARCHAR(255) NULL,
  `idAutora` INT NOT NULL,
  PRIMARY KEY (`ISBN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wypożyczenie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wypożyczenie` (
  `idwypożyczenia` INT NOT NULL,
  `idCzytelnika` INT NOT NULL,
  `czas` DATE NULL,
  PRIMARY KEY (`idwypożyczenia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autorzy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autorzy` (
  `idAutora` INT NOT NULL,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor_ksiazka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor_ksiazka` (
  `idAutora` INT NOT NULL,
  `autorzy_idAutora` INT NOT NULL,
  `książki_ISBN` INT NOT NULL,
  PRIMARY KEY (`idAutora`),
  INDEX `fk_autor_ksiazka_autorzy_idx` (`autorzy_idAutora` ASC) VISIBLE,
  INDEX `fk_autor_ksiazka_książki1_idx` (`książki_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_autor_ksiazka_autorzy`
    FOREIGN KEY (`autorzy_idAutora`)
    REFERENCES `mydb`.`autorzy` (`idAutora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autor_ksiazka_książki1`
    FOREIGN KEY (`książki_ISBN`)
    REFERENCES `mydb`.`książki` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`książki_has_wypożyczenie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`książki_has_wypożyczenie` (
  `książki_ISBN` INT NOT NULL,
  `wypożyczenie_idwypożyczenia` INT NOT NULL,
  PRIMARY KEY (`książki_ISBN`, `wypożyczenie_idwypożyczenia`),
  INDEX `fk_książki_has_wypożyczenie_wypożyczenie1_idx` (`wypożyczenie_idwypożyczenia` ASC) VISIBLE,
  INDEX `fk_książki_has_wypożyczenie_książki1_idx` (`książki_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_książki_has_wypożyczenie_książki1`
    FOREIGN KEY (`książki_ISBN`)
    REFERENCES `mydb`.`książki` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_książki_has_wypożyczenie_wypożyczenie1`
    FOREIGN KEY (`wypożyczenie_idwypożyczenia`)
    REFERENCES `mydb`.`wypożyczenie` (`idwypożyczenia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autorzy_has_książki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autorzy_has_książki` (
  `autorzy_idAutora` INT NOT NULL,
  `książki_ISBN` INT NOT NULL,
  PRIMARY KEY (`autorzy_idAutora`, `książki_ISBN`),
  INDEX `fk_autorzy_has_książki_książki1_idx` (`książki_ISBN` ASC) VISIBLE,
  INDEX `fk_autorzy_has_książki_autorzy1_idx` (`autorzy_idAutora` ASC) VISIBLE,
  CONSTRAINT `fk_autorzy_has_książki_autorzy1`
    FOREIGN KEY (`autorzy_idAutora`)
    REFERENCES `mydb`.`autorzy` (`idAutora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autorzy_has_książki_książki1`
    FOREIGN KEY (`książki_ISBN`)
    REFERENCES `mydb`.`książki` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
