-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 10:11:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `idEvent` INT NOT NULL AUTO_INCREMENT,
  `Nazwa Eventu` VARCHAR(45) NOT NULL,
  `Data` DATE NOT NULL,
  `Miasto` VARCHAR(45) NOT NULL,
  `Ulica` VARCHAR(45) NOT NULL,
  `Przychód` INT NOT NULL,
  `Koszt` INT NOT NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`idEvent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Firma Eventowa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Firma Eventowa` (
  `Event_idEvent` INT NOT NULL,
  `Pracownik` VARCHAR(45) NULL,
  PRIMARY KEY (`Event_idEvent`),
  CONSTRAINT `fk_Firma Eventowa_Event`
    FOREIGN KEY (`Event_idEvent`)
    REFERENCES `mydb`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kontrahent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kontrahent` (
  `ID Kontrahenta` INT NOT NULL AUTO_INCREMENT,
  `Nazwa Kontrahenta` VARCHAR(45) NOT NULL,
  `Ulica` VARCHAR(45) NOT NULL,
  `Numer budynku` VARCHAR(45) NULL,
  `Miasto` VARCHAR(45) NOT NULL,
  `Kod pocztowy` VARCHAR(45) NOT NULL,
  `Numer lokalu` VARCHAR(45) NULL,
  `Kontrahentcol` VARCHAR(45) NULL,
  PRIMARY KEY (`ID Kontrahenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pracownik` (
  `idPracownik` INT NOT NULL AUTO_INCREMENT,
  `Imie` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Stanowisko` VARCHAR(45) NOT NULL,
  `Dział` VARCHAR(45) NOT NULL,
  `Pensja` VARCHAR(45) NULL,
  `Firma Eventowa_Event_idEvent` INT NOT NULL,
  PRIMARY KEY (`idPracownik`, `Firma Eventowa_Event_idEvent`),
  INDEX `fk_Pracownik_Firma Eventowa1_idx` (`Firma Eventowa_Event_idEvent` ASC) VISIBLE,
  CONSTRAINT `fk_Pracownik_Firma Eventowa1`
    FOREIGN KEY (`Firma Eventowa_Event_idEvent`)
    REFERENCES `mydb`.`Firma Eventowa` (`Event_idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rozliczenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rozliczenia` (
  `idRozliczenia` INT NOT NULL,
  `dokument` VARCHAR(45) NULL,
  `Event_idEvent` INT NOT NULL,
  PRIMARY KEY (`idRozliczenia`, `Event_idEvent`),
  INDEX `fk_Rozliczenia_Event1_idx` (`Event_idEvent` ASC) VISIBLE,
  CONSTRAINT `fk_Rozliczenia_Event1`
    FOREIGN KEY (`Event_idEvent`)
    REFERENCES `mydb`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kontrahent_has_Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kontrahent_has_Event` (
  `Kontrahent_ID Kontrahenta` INT NOT NULL,
  `Event_idEvent` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Kontrahent_has_Eventcol` VARCHAR(45) NULL,
  PRIMARY KEY (`Kontrahent_ID Kontrahenta`, `Event_idEvent`),
  INDEX `fk_Kontrahent_has_Event_Event1_idx` (`Event_idEvent` ASC) VISIBLE,
  INDEX `fk_Kontrahent_has_Event_Kontrahent1_idx` (`Kontrahent_ID Kontrahenta` ASC) VISIBLE,
  CONSTRAINT `fk_Kontrahent_has_Event_Kontrahent1`
    FOREIGN KEY (`Kontrahent_ID Kontrahenta`)
    REFERENCES `mydb`.`Kontrahent` (`ID Kontrahenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kontrahent_has_Event_Event1`
    FOREIGN KEY (`Event_idEvent`)
    REFERENCES `mydb`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pracownik_has_Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pracownik_has_Event` (
  `Pracownik_idPracownik` INT NOT NULL,
  `Event_idEvent` INT NOT NULL,
  PRIMARY KEY (`Pracownik_idPracownik`, `Event_idEvent`),
  INDEX `fk_Pracownik_has_Event_Event1_idx` (`Event_idEvent` ASC) VISIBLE,
  INDEX `fk_Pracownik_has_Event_Pracownik1_idx` (`Pracownik_idPracownik` ASC) VISIBLE,
  CONSTRAINT `fk_Pracownik_has_Event_Pracownik1`
    FOREIGN KEY (`Pracownik_idPracownik`)
    REFERENCES `mydb`.`Pracownik` (`idPracownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pracownik_has_Event_Event1`
    FOREIGN KEY (`Event_idEvent`)
    REFERENCES `mydb`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
